version: '3.8'

services:
  photobomb-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUST_VERSION: 1.85.1
        APP_NAME: photobomb-backend
    ports:
      - "127.0.0.1:3002:3002"
    environment:
      - RUST_LOG=info
    platform: linux/arm64
    restart: unless-stopped
