events {}

http {
    # Define rate limiting constraints
    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;
    limit_req_zone $binary_remote_addr zone=strictlimit:10m rate=2r/s;

    server {
        listen 80;
        server_name my-domain.com;
        
        location /api/ {
            # General API (moderate rate limiting)
            limit_req zone=mylimit burst=20;
            proxy_pass http://host.docker.internal:3002/api/;
            client_max_body_size 5M;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
                
        location /api/upload {
            # Sensitive API (strict rate limiting)
            limit_req zone=strictlimit burst=5;
            proxy_pass http://host.docker.internal:3002/api/;
            client_max_body_size 5M;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location / {
            root /var/local/frontend;
            index index.html index.htm;
            try_files $uri $uri/ =404;
        }
        
        # Deny access to hidden files (e.g., .git, .env)
        location ~ /\. {
            deny all;
        }
        
        # Deny access to sensitive file extensions
        location ~* \.(bak|conf|log|sh|sql)$ {
            deny all;
        }
        
        # Prevent common web attacks like XSS or clickjacking.
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";
        add_header X-XSS-Protection "1; mode=block";
        add_header Content-Security-Policy "default-src 'self'; script-src 'self'; object-src 'none';";
    }
}
